Repository Programmers-AI-3/Face_Flow, pull requests merged in 2022-05, with the labels that each got.

#1 장고 프로젝트 기본 구성
  Face_Flow/Face_Flow/__init__.py
  Face_Flow/Face_Flow/asgi.py
  Face_Flow/Face_Flow/settings.py
  Face_Flow/Face_Flow/urls.py
  Face_Flow/Face_Flow/wsgi.py
  Face_Flow/db.sqlite3
  Face_Flow/manage.py
  Face_Flow/video/__init__.py
  Face_Flow/video/admin.py
  Face_Flow/video/apps.py
  Face_Flow/video/migrations/__init__.py
  Face_Flow/video/migrations/__pycache__/__init__.cpython-38.pyc
  Face_Flow/video/models.py
  Face_Flow/video/templates/index.html
  Face_Flow/video/tests.py
  Face_Flow/video/views.py
Labels: demo

#10 DH 모델로 학습 결과 이미지 대체
  .DS_Store
  README.md
Labels: documentation

#9 이미지 변환 및 라벨 생성기, yolov3 학습기 추가
  etc/image_resizer&label_extractor.ipynb
  etc/yolov3_trainer.ipynb
  requirements.txt
Labels: demo

#14 rename file
  etc/pro_image_extractor.ipynb
Labels: documentation

#17 datasets 배포
  .DS_Store
  README.md
Labels: documentation, demo
